# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'
    
    - name: Unit test
      run: go test -v ./cmd/  -coverprofile=coverage.out
    
    - name: Generate coverage report
      run: go tool cover -html coverage.out -o coverage.html
      
    - name: Archive test coverage result
      uses: actions/upload-artifact@v3
      with:
        name: coverage.html
        path: |
          .

    - name: Build
      run: go build -v -o gsearch ./cmd/
    - name: Archive built binary
      uses: actions/upload-artifact@v3
      with:
        name: gsearch
        path: |
          .
